/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.educavalcante.cinemanager.views;

import br.com.educavalcante.cinemanager.controllers.FilmeController;
import br.com.educavalcante.cinemanager.controllers.IngressoController;
import br.com.educavalcante.cinemanager.controllers.SalaController;
import br.com.educavalcante.cinemanager.controllers.SessaoController;
import br.com.educavalcante.cinemanager.models.entities.Filme;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.text.NumberFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

public class FilmeDialog extends javax.swing.JDialog {
    private Filme filmeAtual;
    private final FilmeController controller;
    private final SalaController salaController;
    private final SessaoController sessaoController;
    private final TelaAdmin parent;
    
    public FilmeDialog(TelaAdmin parent, boolean modal, FilmeController controller, SalaController salaController, SessaoController sessaoController) {
        super(parent, modal);
        this.controller = controller;
        this.salaController = salaController;
        this.sessaoController = sessaoController;
        this.parent = parent;
        initComponents();
        deleteButton.setVisible(false);
        createSessionButton.setVisible(false);
    }
    
    public FilmeDialog(TelaAdmin parent, boolean modal, FilmeController controller, int filmeId, SalaController salaController, SessaoController sessaoController) {
        super(parent, modal);
        this.controller = controller;
        this.salaController = salaController;
        this.sessaoController = sessaoController;
        this.parent = parent;
        initComponents();

        filmeAtual = controller.buscarFilmePorId(filmeId);
        if(!filmeAtual.isEmCartaz()) {
            createSessionButton.setVisible(false);
        }
        preencherCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        titleField = new JTextField();
        jScrollPane1 = new JScrollPane();
        sinopseField = new JTextArea();
        genreMenuField = new JComboBox<>();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        durationField = new JFormattedTextField();
        jLabel6 = new JLabel();
        saveButton = new JButton();
        deleteButton = new JButton();
        createSessionButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar/Editar Filme");

        jLabel1.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Adicionar/Editar Filme");

        sinopseField.setColumns(20);
        sinopseField.setRows(5);
        jScrollPane1.setViewportView(sinopseField);

        genreMenuField.setModel(new DefaultComboBoxModel<>(new String[] { "Drama", "Romance", "Ação", "Terror", "Comédia", "Ficção Científica", "Infantil", "Fantasia", "Suspense", "Mistério", "Aventura", "Documentário", "Musical" }));

        jLabel2.setText("Título:");

        jLabel3.setText("Sinopse:");

        jLabel4.setText("Gênero:");

        jLabel5.setText("Duração:");

        durationField.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(NumberFormat.getIntegerInstance())));

        jLabel6.setText("min");

        saveButton.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        saveButton.setForeground(new Color(0, 204, 0));
        saveButton.setText("Salvar");
        saveButton.addActionListener(this::saveButtonActionPerformed);

        deleteButton.setFont(new Font("sansserif", 1, 12)); // NOI18N
        deleteButton.setForeground(new Color(255, 51, 51));
        deleteButton.setText("Excluir");
        deleteButton.addActionListener(this::deleteButtonActionPerformed);

        createSessionButton.setFont(new Font("sansserif", 1, 12)); // NOI18N
        createSessionButton.setText("Criar Sessão");
        createSessionButton.addActionListener(this::createSessionButtonActionPerformed);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(genreMenuField, GroupLayout.PREFERRED_SIZE, 270, GroupLayout.PREFERRED_SIZE))
                            .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 270, GroupLayout.PREFERRED_SIZE))
                            .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(titleField, GroupLayout.PREFERRED_SIZE, 270, GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45))
                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deleteButton, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createSessionButton)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saveButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(durationField, GroupLayout.PREFERRED_SIZE, 270, GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(titleField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(genreMenuField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(durationField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(deleteButton)
                    .addComponent(createSessionButton))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String titulo = (String) titleField.getText().trim();
        String sinopse = (String) sinopseField.getText().trim();
        String genero = (String) genreMenuField.getSelectedItem();
        
        if(titulo.isBlank() || sinopse.isBlank() || genero.isBlank() || durationField.getText().trim().isBlank()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.", "Erro ao salvar", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int duracao = Integer.parseInt(durationField.getText().trim());
        
        if (filmeAtual == null) {
            controller.cadastrarFilme(titulo, sinopse, genero, duracao);
        } else {
            controller.editarFilme(filmeAtual.getId(), titulo, sinopse, genero, duracao);
        }
        EventQueue.invokeLater(() -> {
            parent.carregarFilmes();
            this.dispose();
        });
    }//GEN-LAST:event_saveButtonActionPerformed

    private void deleteButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (filmeAtual == null) return;

        int confirm = JOptionPane.showConfirmDialog(this, 
            "Tem certeza que deseja excluir este filme?", 
            "Confirmar exclusão", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            controller.removerFilme(filmeAtual.getId());
            
            EventQueue.invokeLater(() -> {
                parent.carregarFilmes();
                this.dispose();
            });
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void createSessionButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_createSessionButtonActionPerformed
        new SessaoDialog(parent, true, sessaoController, salaController, controller, filmeAtual.getId()).setVisible(true);
    }//GEN-LAST:event_createSessionButtonActionPerformed

    private void preencherCampos() {
        titleField.setText(filmeAtual.getTitulo());
        sinopseField.setText(filmeAtual.getSinopse());
        genreMenuField.setSelectedItem(filmeAtual.getGenero());
        durationField.setText(String.valueOf(filmeAtual.getDuracao()));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton createSessionButton;
    private JButton deleteButton;
    private JFormattedTextField durationField;
    private JComboBox<String> genreMenuField;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JScrollPane jScrollPane1;
    private JButton saveButton;
    private JTextArea sinopseField;
    private JTextField titleField;
    // End of variables declaration//GEN-END:variables
}
