/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.educavalcante.cinemanager.views;

import br.com.educavalcante.cinemanager.controllers.SalaController;
import br.com.educavalcante.cinemanager.models.entities.Sala;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.text.NumberFormat;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

public class SalaDialog extends javax.swing.JDialog {
    private Sala salaAtual;
    private final SalaController controller;
    private TelaAdmin parent;
    
    public SalaDialog(TelaAdmin parent, boolean modal, SalaController controller) {
        super(parent, modal);
        this.parent = parent;
        this.controller = controller;
        initComponents();
        deleteButton.setVisible(false);
    }
    
    public SalaDialog(TelaAdmin parent, boolean modal, SalaController controller, int salaId) {
        super(parent, modal);
        this.parent = parent;
        this.controller = controller;
        initComponents();
        salaAtual = controller.buscarSalaPorId(salaId);
        preencherCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel5 = new JLabel();
        numberField = new JFormattedTextField();
        jLabel6 = new JLabel();
        rowsField = new JFormattedTextField();
        seatsField = new JFormattedTextField();
        jLabel7 = new JLabel();
        deleteButton = new JButton();
        saveButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar/Editar Sala");

        jLabel1.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Adicionar/Editar Sala");

        jLabel5.setText("Número da sala:");

        numberField.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(NumberFormat.getIntegerInstance())));

        jLabel6.setText("Total de fileiras:");

        rowsField.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(NumberFormat.getIntegerInstance())));

        seatsField.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(NumberFormat.getIntegerInstance())));

        jLabel7.setText("Nº de assentos por fileira:");

        deleteButton.setFont(new Font("sansserif", 1, 12)); // NOI18N
        deleteButton.setForeground(new Color(255, 51, 51));
        deleteButton.setText("Excluir");
        deleteButton.addActionListener(this::deleteButtonActionPerformed);

        saveButton.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        saveButton.setForeground(new Color(0, 204, 0));
        saveButton.setText("Salvar");
        saveButton.addActionListener(this::saveButtonActionPerformed);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(deleteButton, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                .addComponent(seatsField, GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                .addComponent(rowsField)
                                .addComponent(numberField))
                            .addComponent(saveButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(numberField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(rowsField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(seatsField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(saveButton))
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (salaAtual == null) return;

        int confirm = JOptionPane.showConfirmDialog(this,
            "Tem certeza que deseja excluir esta sala?",
            "Confirmar exclusão", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            controller.removerSala(salaAtual.getId());

            EventQueue.invokeLater(() -> {
                parent.carregarSalas();
                this.dispose();
            });
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void saveButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(numberField.getText().isBlank() || rowsField.getText().isBlank() || seatsField.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.", "Erro ao salvar", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int numero = Integer.parseInt(numberField.getText().trim());
        int totalFileiras = Integer.parseInt(rowsField.getText().trim());
        int totalAssentosPorFileira = Integer.parseInt(seatsField.getText().trim());

        if (salaAtual == null) {
            controller.cadastrarSala(numero, totalFileiras, totalAssentosPorFileira);
        } else {
            controller.editarSala(salaAtual.getId(), numero, totalFileiras, totalAssentosPorFileira);
        }
        EventQueue.invokeLater(() -> {
            parent.carregarSalas();
            this.dispose();
        });
    }//GEN-LAST:event_saveButtonActionPerformed

    private void preencherCampos() {
        numberField.setText(String.valueOf(salaAtual.getNumero()));
        rowsField.setText(String.valueOf(salaAtual.getTotalFileiras()));
        seatsField.setText(String.valueOf(salaAtual.getTotalAssentosPorFileira()));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton deleteButton;
    private JLabel jLabel1;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JFormattedTextField numberField;
    private JFormattedTextField rowsField;
    private JButton saveButton;
    private JFormattedTextField seatsField;
    // End of variables declaration//GEN-END:variables
}
