/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.educavalcante.cinemanager.views;

import br.com.educavalcante.cinemanager.controllers.FilmeController;
import br.com.educavalcante.cinemanager.controllers.SalaController;
import br.com.educavalcante.cinemanager.controllers.SessaoController;
import br.com.educavalcante.cinemanager.models.entities.Filme;
import br.com.educavalcante.cinemanager.models.entities.Sala;
import br.com.educavalcante.cinemanager.models.entities.Sessao;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.util.Date;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.time.LocalDateTime;
import java.time.ZoneId;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.LayoutStyle;
import javax.swing.SpinnerDateModel;
import javax.swing.WindowConstants;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

public class SessaoDialog extends javax.swing.JDialog {
    private Sessao sessaoAtual;
    private final SessaoController sessaoController;
    private final SalaController salaController;
    private final int filmeId;
    private final TelaAdmin parent;
    
    public SessaoDialog(TelaAdmin parent, boolean modal, SessaoController controller, SalaController salaController, FilmeController filmeController, int filmeId) {
        super(parent, modal);
        this.parent = parent;
        this.sessaoController = controller;
        this.salaController = salaController;
        this.filmeId = filmeId;
        initComponents();
        deleteButton.setVisible(false);
        
        Filme filme = filmeController.buscarFilmePorId(filmeId);
        titleLabel.setText("Filme: " + filme.getTitulo());
    }
    
    public SessaoDialog(TelaAdmin parent, boolean modal, SessaoController controller, SalaController salaController, FilmeController filmeController, int sessaoId, int filmeId) {
        super(parent, modal);
        this.parent = parent;
        this.sessaoController = controller;
        this.salaController = salaController;
        this.filmeId = filmeId;
        initComponents();
        sessaoAtual = controller.buscarSessaoPorId(sessaoId);
        preencherCampos();
        
        Filme filme = filmeController.buscarFilmePorId(filmeId);
        titleLabel.setText("Filme: " + filme.getTitulo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel5 = new JLabel();
        numberField = new JFormattedTextField();
        priceField = new JFormattedTextField();
        jLabel7 = new JLabel();
        deleteButton = new JButton();
        saveButton = new JButton();
        titleLabel = new JLabel();
        dataHoraSpinner = new JSpinner();
        jLabel3 = new JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar/Editar Sessão");

        jLabel1.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Adicionar/Editar Sessão");

        jLabel5.setText("Número da sala:");

        numberField.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(NumberFormat.getIntegerInstance())));

        priceField.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0.00"))));

        jLabel7.setText("Preço Base:");

        deleteButton.setFont(new Font("sansserif", 1, 12)); // NOI18N
        deleteButton.setForeground(new Color(255, 51, 51));
        deleteButton.setText("Excluir");
        deleteButton.addActionListener(this::deleteButtonActionPerformed);

        saveButton.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        saveButton.setForeground(new Color(0, 204, 0));
        saveButton.setText("Salvar");
        saveButton.addActionListener(this::saveButtonActionPerformed);

        titleLabel.setText("Filme:");

        dataHoraSpinner.setModel(new SpinnerDateModel());

        jLabel3.setText("Data e Hora:");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addComponent(titleLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(deleteButton, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(priceField, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(numberField, GroupLayout.Alignment.LEADING)
                            .addComponent(saveButton)
                            .addComponent(dataHoraSpinner, GroupLayout.Alignment.LEADING))))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(dataHoraSpinner, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(numberField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(priceField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(saveButton))
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (sessaoAtual == null) return;

        int confirm = JOptionPane.showConfirmDialog(this,
            "Tem certeza que deseja excluir esta sessão?",
            "Confirmar exclusão", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            sessaoController.excluirSessao(sessaoAtual.getId());

            EventQueue.invokeLater(() -> {
                parent.carregarSessoes();
                this.dispose();
            });
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void saveButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(numberField.getText().isBlank() || dataHoraSpinner.getValue().toString().isBlank() || priceField.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.", "Erro ao salvar", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Date dataSelecionada = (Date) dataHoraSpinner.getValue();
        LocalDateTime dataHora = dataSelecionada.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
        
        double precoBase = ((Number) priceField.getValue()).doubleValue();

        if (sessaoAtual == null) {
            int numero = Integer.parseInt(numberField.getText().trim());
            Sala sala = salaController.buscarSalaPorNumero(numero);
            
            if(sala == null) {
                JOptionPane.showMessageDialog(null, "Sala não encontrada.");
                return;
            }
        
            sessaoController.cadastrarSessao(this.filmeId, sala.getId(), dataHora, precoBase);
        } else {
            sessaoController.editarSessao(sessaoAtual.getId(), dataHora, precoBase);
        }
        EventQueue.invokeLater(() -> {
            parent.carregarSessoes();
            this.dispose();
        });
    }//GEN-LAST:event_saveButtonActionPerformed

    private void preencherCampos() {
        Sala sala = salaController.buscarSalaPorId(sessaoAtual.getSalaId());
        numberField.setText(String.valueOf(sala.getNumero()));
        
        LocalDateTime dataHora = sessaoAtual.getDataHora();
        Date date = Date.from(dataHora.atZone(ZoneId.systemDefault()).toInstant());
        dataHoraSpinner.setValue(date);
        
        priceField.setText(String.valueOf(sessaoAtual.getPrecoBase()));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JSpinner dataHoraSpinner;
    private JButton deleteButton;
    private JLabel jLabel1;
    private JLabel jLabel3;
    private JLabel jLabel5;
    private JLabel jLabel7;
    private JFormattedTextField numberField;
    private JFormattedTextField priceField;
    private JButton saveButton;
    private JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
