/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.educavalcante.cinemanager.views;

import br.com.educavalcante.cinemanager.controllers.SalaController;
import br.com.educavalcante.cinemanager.controllers.SessaoController;
import br.com.educavalcante.cinemanager.models.DAOs.SalaDAO;
import br.com.educavalcante.cinemanager.models.entities.Filme;
import br.com.educavalcante.cinemanager.models.entities.Ingresso;
import br.com.educavalcante.cinemanager.models.entities.Sala;
import br.com.educavalcante.cinemanager.models.entities.Sessao;
import br.com.educavalcante.cinemanager.models.entities.Usuario;
import br.com.educavalcante.cinemanager.utils.TipoIngresso;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.text.NumberFormat;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.stream.Collectors;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JToggleButton;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

public class TelaSessao extends javax.swing.JFrame {
    private final Sessao sessaoAtual;
    private final Sala sala;
    private final SessaoController sessaoController;
    private final SalaController salaController;
    private final Usuario user;
    
    private int fileiraSelecionada = -1;
    private int numeroSelecionado = -1;
    NumberFormat moeda = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
    
    public TelaSessao(Filme filme, Sessao sessao, SessaoController sessaoController, Usuario usuario) {
        this.sessaoAtual = sessao;
        this.sessaoController = sessaoController;
        this.user = usuario;
        this.salaController = new SalaController(new SalaDAO());
        sala = salaController.buscarSalaPorId(sessaoAtual.getSalaId());
        initComponents();
        
        titleLabel.setText(titleLabel.getText() + " " + filme.getTitulo());
        roomLabel.setText(roomLabel.getText() + " " + sala.getNumero());
        
        DateTimeFormatter fmtData = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        DateTimeFormatter fmtHora = DateTimeFormatter.ofPattern("HH:mm");
        dateTimeLabel.setText(dateTimeLabel.getText() + " " + sessao.getDataHora().format(fmtHora) + " - " + sessao.getDataHora().format(fmtData));
        
        priceLabel.setText(priceLabel.getText() + " " + moeda.format(sessao.getPrecoBase()));
        
        carregarAssentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sessionLabel = new JLabel();
        titleLabel = new JLabel();
        roomLabel = new JLabel();
        dateTimeLabel = new JLabel();
        priceLabel = new JLabel();
        jScrollPane1 = new JScrollPane();
        painelSessao = new JPanel();
        jLabel1 = new JLabel();
        inteiraButton = new JButton();
        meiaButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CineManager");

        sessionLabel.setFont(new Font("Segoe UI", 1, 24)); // NOI18N
        sessionLabel.setText("Sessão");

        titleLabel.setText("Filme:");

        roomLabel.setText("Sala:");

        dateTimeLabel.setText("Data e Hora:");

        priceLabel.setText("Preço Base:");

        GroupLayout painelSessaoLayout = new GroupLayout(painelSessao);
        painelSessao.setLayout(painelSessaoLayout);
        painelSessaoLayout.setHorizontalGroup(painelSessaoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        painelSessaoLayout.setVerticalGroup(painelSessaoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(painelSessao);

        jLabel1.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Assentos disponíveis:");

        inteiraButton.setText("Comprar Inteira");
        inteiraButton.addActionListener(this::inteiraButtonActionPerformed);

        meiaButton.setText("Comprar Meia");
        meiaButton.addActionListener(this::meiaButtonActionPerformed);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sessionLabel, GroupLayout.PREFERRED_SIZE, 188, GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(meiaButton)
                        .addGap(18, 18, 18)
                        .addComponent(inteiraButton)
                        .addGap(16, 16, 16))))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 215, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(titleLabel, GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                            .addComponent(roomLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateTimeLabel, GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(priceLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sessionLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(dateTimeLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(roomLabel)
                    .addComponent(priceLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(inteiraButton)
                    .addComponent(meiaButton))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inteiraButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_inteiraButtonActionPerformed
        comprar(TipoIngresso.INTEIRA);
    }//GEN-LAST:event_inteiraButtonActionPerformed

    private void meiaButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_meiaButtonActionPerformed
        comprar(TipoIngresso.MEIA);
    }//GEN-LAST:event_meiaButtonActionPerformed

    public void comprar(TipoIngresso tipo) {
        if(fileiraSelecionada == -1 || numeroSelecionado == -1) {
            return;
        }
        
        String subtotal = tipo == TipoIngresso.MEIA ? moeda.format(sessaoAtual.getPrecoBase() / 2) : moeda.format(sessaoAtual.getPrecoBase());
        int confirm = JOptionPane.showConfirmDialog(null,
                "Subtotal: " + subtotal,
                "Finalizar Compra",
                JOptionPane.OK_CANCEL_OPTION);
        
        if(confirm == JOptionPane.OK_OPTION) {
            Ingresso ingresso = sessaoController.comprarIngresso(sessaoAtual.getId(), user.getId(), new int[] {fileiraSelecionada, numeroSelecionado}, tipo);
            
            if(ingresso == null) {
                JOptionPane.showMessageDialog(null, "Erro ao finalizar compra", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            JOptionPane.showMessageDialog(null, "Compra confirmada!");
            dispose();
        }
    }
    
    public void carregarAssentos() {
        List<int[]> ocupados = sessaoController.buscarAssentosDisponiveis(sessaoAtual.getId());
        
        Set<String> ocupadosSet = ocupados.stream().map(a -> a[0] + "-" + a[1]).collect(Collectors.toSet());
        
        JPanel painelAssentos = new JPanel(new GridLayout(sala.getTotalFileiras(), sala.getTotalAssentosPorFileira(), 5, 5));

        for (int fileira = 1; fileira <= sala.getTotalFileiras(); fileira++) {
            for (int numero = 1; numero <= sala.getTotalAssentosPorFileira(); numero++) {
                int assentoReal = (fileira - 1) * sala.getTotalAssentosPorFileira() + numero;
                JToggleButton botao = new JToggleButton("" + assentoReal);
                botao.setOpaque(true);
                botao.setBorderPainted(false);
                botao.setFocusPainted(false);
                botao.setForeground(Color.BLACK);

                String chave = fileira + "-" + numero;
                if (ocupadosSet.contains(chave)) {
                    botao.setEnabled(false);
                    botao.setBackground(new Color(255, 51, 51));
                } else {
                    botao.setBackground(new Color(0, 153, 51));
                }
                
                final int f = fileira;
                final int n = numero;
                
                botao.addActionListener(e -> {
                    if(botao.isSelected()) {
                        botao.setBackground(Color.YELLOW);
                        fileiraSelecionada = f;
                        numeroSelecionado = n;
                    } else {
                        botao.setBackground(new Color(0, 153, 51));
                        fileiraSelecionada = -1;
                        numeroSelecionado = -1;
                    }
                });

                painelAssentos.add(botao);
            }
        }
        
        jScrollPane1.setViewportView(painelAssentos);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel dateTimeLabel;
    private JButton inteiraButton;
    private JLabel jLabel1;
    private JScrollPane jScrollPane1;
    private JButton meiaButton;
    private JPanel painelSessao;
    private JLabel priceLabel;
    private JLabel roomLabel;
    private JLabel sessionLabel;
    private JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
