package br.com.educavalcante.cinemanager.views;

import br.com.educavalcante.cinemanager.controllers.FilmeController;
import br.com.educavalcante.cinemanager.controllers.IngressoController;
import br.com.educavalcante.cinemanager.controllers.SalaController;
import br.com.educavalcante.cinemanager.controllers.SessaoController;
import br.com.educavalcante.cinemanager.controllers.UsuarioController;
import br.com.educavalcante.cinemanager.models.DAOs.IngressoDAO;
import br.com.educavalcante.cinemanager.models.DAOs.SalaDAO;
import br.com.educavalcante.cinemanager.models.DAOs.SessaoDAO;
import br.com.educavalcante.cinemanager.models.DAOs.UsuarioDAO;
import br.com.educavalcante.cinemanager.models.entities.Filme;
import br.com.educavalcante.cinemanager.models.entities.Sala;
import br.com.educavalcante.cinemanager.models.entities.Sessao;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.NumberFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.border.LineBorder;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;

public class TelaAdmin extends javax.swing.JFrame {
    private final CardLayout cardLayout;
    private final FilmeController filmeController;
    private final SalaController salaController;
    private final SessaoController sessaoController;
    private final IngressoController ingressoController;

    public TelaAdmin(FilmeController controller) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("CineManager");
        cardLayout = (CardLayout) parentPanel.getLayout();
        filmeController = controller;
        salaController = new SalaController(new SalaDAO());
        ingressoController = new IngressoController(new IngressoDAO());
        sessaoController = new SessaoController(new SessaoDAO(), ingressoController);
        
        carregarFilmes();
        carregarSalas();
        carregarSessoes();
        
        carregarVendas();
        
        DefaultTableModel model = (DefaultTableModel) tabelaFilmes.getModel();
        
        model.addTableModelListener(e -> {
            if (e.getType() == TableModelEvent.UPDATE && e.getColumn() == 3) {
                int row = e.getFirstRow();
                int id = (int) model.getValueAt(row, 0);
                boolean emCartaz = (boolean) model.getValueAt(row, 3);

                if (emCartaz) {
                    filmeController.colocarEmCartaz(id);
                } else {
                    filmeController.removerDoCartaz(id);
                }
            }
        });
        
        tabelaFilmes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                int col = tabelaFilmes.columnAtPoint(evt.getPoint());
                if (col == 3) {
                    tabelaFilmes.setToolTipText("Marque para colocar o filme em cartaz");
                } else {
                    tabelaFilmes.setToolTipText(null);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navBarPanel = new JPanel();
        dashboardButton = new JButton();
        movieButton = new JButton();
        roomButton = new JButton();
        sessionButton = new JButton();
        signOutButton = new JButton();
        parentPanel = new JPanel();
        dashboardPanel = new JPanel();
        jLabel1 = new JLabel();
        jPanel1 = new JPanel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        valueLabel = new JLabel();
        moviesPanel = new JPanel();
        jScrollPane1 = new JScrollPane();
        tabelaFilmes = new JTable();
        addMovieButton = new JButton();
        jLabel2 = new JLabel();
        checkBox = new JCheckBox();
        roomsPanel = new JPanel();
        jLabel3 = new JLabel();
        addRoomButton = new JButton();
        jScrollPane2 = new JScrollPane();
        tabelaSalas = new JTable();
        sessionsPanel = new JPanel();
        jLabel4 = new JLabel();
        jScrollPane3 = new JScrollPane();
        tabelaSessoes = new JTable();
        helpButton = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");
        setBackground(new Color(51, 51, 51));

        navBarPanel.setBackground(new Color(51, 51, 51));

        dashboardButton.setText("Dashboard");
        dashboardButton.addActionListener(this::dashboardButtonActionPerformed);

        movieButton.setText("Filmes");
        movieButton.addActionListener(this::movieButtonActionPerformed);

        roomButton.setText("Salas");
        roomButton.addActionListener(this::roomButtonActionPerformed);

        sessionButton.setText("Sessões");
        sessionButton.addActionListener(this::sessionButtonActionPerformed);

        signOutButton.setText("Sair");
        signOutButton.addActionListener(this::signOutButtonActionPerformed);

        GroupLayout navBarPanelLayout = new GroupLayout(navBarPanel);
        navBarPanel.setLayout(navBarPanelLayout);
        navBarPanelLayout.setHorizontalGroup(navBarPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(navBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboardButton)
                .addGap(18, 18, 18)
                .addComponent(movieButton)
                .addGap(18, 18, 18)
                .addComponent(roomButton)
                .addGap(18, 18, 18)
                .addComponent(sessionButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signOutButton)
                .addContainerGap())
        );
        navBarPanelLayout.setVerticalGroup(navBarPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, navBarPanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(navBarPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(dashboardButton)
                    .addComponent(movieButton)
                    .addComponent(roomButton)
                    .addComponent(sessionButton)
                    .addComponent(signOutButton))
                .addContainerGap())
        );

        parentPanel.setBackground(new Color(51, 51, 51));
        parentPanel.setLayout(new CardLayout());

        jLabel1.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Bem-vindo!");

        jPanel1.setBackground(new Color(51, 51, 51));
        jPanel1.setBorder(new LineBorder(new Color(51, 51, 51), 1, true));
        jPanel1.setForeground(new Color(242, 242, 242));

        jLabel5.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new Color(0, 153, 51));
        jLabel5.setText("Total de Vendas");

        jLabel6.setFont(new Font("Segoe UI", 1, 48)); // NOI18N
        jLabel6.setForeground(new Color(0, 153, 51));
        jLabel6.setText("R$");

        valueLabel.setFont(new Font("Segoe UI", 1, 48)); // NOI18N
        valueLabel.setForeground(new Color(0, 153, 51));
        valueLabel.setText("0,00");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(175, 175, 175))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel6)
                .addGap(32, 32, 32)
                .addComponent(valueLabel)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(valueLabel))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        GroupLayout dashboardPanelLayout = new GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(dashboardPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(dashboardPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel1))
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        dashboardPanelLayout.setVerticalGroup(dashboardPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(81, 81, 81)
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        parentPanel.add(dashboardPanel, "dashboardCard");

        moviesPanel.setBackground(new Color(51, 51, 51));

        tabelaFilmes.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Título", "Gênero", "Em Cartaz"
            }
        ) {
            Class[] types = new Class [] {
                Integer.class, String.class, String.class, Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaFilmes.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                tabelaFilmesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaFilmes);
        if (tabelaFilmes.getColumnModel().getColumnCount() > 0) {
            tabelaFilmes.getColumnModel().getColumn(1).setHeaderValue("Título");
            tabelaFilmes.getColumnModel().getColumn(2).setHeaderValue("Gênero");
            tabelaFilmes.getColumnModel().getColumn(3).setHeaderValue("Em Cartaz");
        }

        addMovieButton.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        addMovieButton.setText("+");
        addMovieButton.addActionListener(this::addMovieButtonActionPerformed);

        jLabel2.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new Color(255, 255, 255));
        jLabel2.setText("Filmes");

        checkBox.setText("Mostrar apenas filmes em cartaz");
        checkBox.addActionListener(this::checkBoxActionPerformed);

        GroupLayout moviesPanelLayout = new GroupLayout(moviesPanel);
        moviesPanel.setLayout(moviesPanelLayout);
        moviesPanelLayout.setHorizontalGroup(moviesPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(GroupLayout.Alignment.TRAILING, moviesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkBox)
                .addGap(31, 31, 31)
                .addComponent(addMovieButton)
                .addContainerGap())
        );
        moviesPanelLayout.setVerticalGroup(moviesPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, moviesPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(moviesPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addMovieButton)
                    .addComponent(checkBox))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        parentPanel.add(moviesPanel, "moviesCard");

        roomsPanel.setBackground(new Color(51, 51, 51));

        jLabel3.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new Color(255, 255, 255));
        jLabel3.setText("Salas disponíveis");

        addRoomButton.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        addRoomButton.setText("+");
        addRoomButton.addActionListener(this::addRoomButtonActionPerformed);

        tabelaSalas.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Número da Sala", "Total de Fileiras", "Nº de Assentos por Fileira", "Total de Assentos"
            }
        ) {
            Class[] types = new Class [] {
                Integer.class, Integer.class, Integer.class, Object.class, Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaSalas.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                tabelaSalasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaSalas);

        GroupLayout roomsPanelLayout = new GroupLayout(roomsPanel);
        roomsPanel.setLayout(roomsPanelLayout);
        roomsPanelLayout.setHorizontalGroup(roomsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(roomsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addRoomButton)
                .addContainerGap())
            .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        roomsPanelLayout.setVerticalGroup(roomsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(roomsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roomsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addRoomButton))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE))
        );

        parentPanel.add(roomsPanel, "roomsCard");

        sessionsPanel.setBackground(new Color(51, 51, 51));

        jLabel4.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new Color(255, 255, 255));
        jLabel4.setText("Sessões");

        tabelaSessoes.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Filme", "Sala", "Data e horário", "Preço Base"
            }
        ) {
            Class[] types = new Class [] {
                Integer.class, String.class, Integer.class, String.class, Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaSessoes.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                tabelaSessoesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaSessoes);

        helpButton.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        helpButton.setText("?");
        helpButton.addActionListener(this::helpButtonActionPerformed);

        GroupLayout sessionsPanelLayout = new GroupLayout(sessionsPanel);
        sessionsPanel.setLayout(sessionsPanelLayout);
        sessionsPanelLayout.setHorizontalGroup(sessionsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(sessionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(helpButton)
                .addContainerGap())
            .addComponent(jScrollPane3, GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        sessionsPanelLayout.setVerticalGroup(sessionsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(sessionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sessionsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(helpButton, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );

        parentPanel.add(sessionsPanel, "sessionsCard");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(navBarPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(parentPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navBarPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parentPanel, GroupLayout.PREFERRED_SIZE, 460, GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMovieButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_addMovieButtonActionPerformed
        new FilmeDialog(this, true, filmeController, salaController, sessaoController).setVisible(true);
    }//GEN-LAST:event_addMovieButtonActionPerformed

    private void dashboardButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_dashboardButtonActionPerformed
        cardLayout.show(parentPanel, "dashboardCard");
        carregarVendas();
    }//GEN-LAST:event_dashboardButtonActionPerformed

    private void movieButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_movieButtonActionPerformed
        cardLayout.show(parentPanel, "moviesCard");
    }//GEN-LAST:event_movieButtonActionPerformed

    private void signOutButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_signOutButtonActionPerformed
        new TelaLogin(new UsuarioController(new UsuarioDAO())).setVisible(true);
        dispose();
    }//GEN-LAST:event_signOutButtonActionPerformed

    private void tabelaFilmesMouseClicked(MouseEvent evt) {//GEN-FIRST:event_tabelaFilmesMouseClicked
        if (evt.getClickCount() == 2) { // duplo clique
            int row = tabelaFilmes.getSelectedRow();
            if (row >= 0) {
                int id = (int) tabelaFilmes.getValueAt(row, 0);
                new FilmeDialog(this, true, filmeController, id, salaController, sessaoController).setVisible(true);
            }
        }
    }//GEN-LAST:event_tabelaFilmesMouseClicked

    private void checkBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_checkBoxActionPerformed
        carregarFilmes();
    }//GEN-LAST:event_checkBoxActionPerformed

    private void addRoomButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_addRoomButtonActionPerformed
        new SalaDialog(this, true, salaController).setVisible(true);
    }//GEN-LAST:event_addRoomButtonActionPerformed

    private void tabelaSalasMouseClicked(MouseEvent evt) {//GEN-FIRST:event_tabelaSalasMouseClicked
        if (evt.getClickCount() == 2) { // duplo clique
            int row = tabelaSalas.getSelectedRow();
            if (row >= 0) {
                int id = (int) tabelaSalas.getValueAt(row, 0);
                new SalaDialog(this, true, salaController, id).setVisible(true);
            }
        }
    }//GEN-LAST:event_tabelaSalasMouseClicked

    private void roomButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_roomButtonActionPerformed
        cardLayout.show(parentPanel, "roomsCard");
    }//GEN-LAST:event_roomButtonActionPerformed

    private void sessionButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_sessionButtonActionPerformed
        cardLayout.show(parentPanel, "sessionsCard");
    }//GEN-LAST:event_sessionButtonActionPerformed

    private void tabelaSessoesMouseClicked(MouseEvent evt) {//GEN-FIRST:event_tabelaSessoesMouseClicked
        if (evt.getClickCount() == 2) { // duplo clique
            int row = tabelaSessoes.getSelectedRow();
            if (row >= 0) {
                int id = (int) tabelaSessoes.getValueAt(row, 0);
                Sessao sessao = sessaoController.buscarSessaoPorId(id);
                new SessaoDialog(this, true, sessaoController, salaController, filmeController, id, sessao.getFilmeId()).setVisible(true);
            }
        }
    }//GEN-LAST:event_tabelaSessoesMouseClicked

    private void helpButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        JOptionPane.showMessageDialog(null, """
                                            Para adicionar uma sessão, dê um clique duplo
                                            em um filme na tabela de filmes, certificando-se
                                            antes de que ele esteja em cartaz.""");
    }//GEN-LAST:event_helpButtonActionPerformed
    
    public final void carregarFilmes() {
        List<Filme> filmes;
        
        if(checkBox.isSelected()) {
            filmes = filmeController.listarFilmesEmCartaz();
        } else {
            filmes = filmeController.listarFilmes();
        }

        DefaultTableModel model = (DefaultTableModel) tabelaFilmes.getModel();

        EventQueue.invokeLater(() -> {
            model.setRowCount(0);
            for (Filme filme : filmes) {
                model.addRow(new Object[] {
                    filme.getId(),
                    filme.getTitulo(),
                    filme.getGenero(),
                    filme.isEmCartaz()
                });
            }
        });
    }
    
    public final void carregarSalas() {
        List<Sala> salas = salaController.listarSalas();
        
        DefaultTableModel model = (DefaultTableModel) tabelaSalas.getModel();
        
        EventQueue.invokeLater(() -> {
            model.setRowCount(0);
            for (Sala sala : salas) {
                model.addRow(new Object[] {
                    sala.getId(),
                    sala.getNumero(),
                    sala.getTotalFileiras(),
                    sala.getTotalAssentosPorFileira(),
                    (sala.getTotalFileiras() * sala.getTotalAssentosPorFileira())
                });
            }
        });
    }
    
    public final void carregarSessoes() {
        List<Sessao> sessoes = sessaoController.listarSessoes();
        
        DefaultTableModel model = (DefaultTableModel) tabelaSessoes.getModel();
        
        EventQueue.invokeLater(() -> {
            model.setRowCount(0);
            for (Sessao sessao : sessoes) {
                Filme filme = filmeController.buscarFilmePorId(sessao.getFilmeId());
                Sala sala = salaController.buscarSalaPorId(sessao.getSalaId());
                
                model.addRow(new Object[] {
                    sessao.getId(),
                    filme.getTitulo(),
                    sala.getNumero(),
                    sessao.getDataHora().toString(),
                    sessao.getPrecoBase()
                });
            }
        });
    }
    
    public final void carregarVendas() {
        double total = ingressoController.calcularTotalVendas();

        NumberFormat formato = NumberFormat.getNumberInstance(new Locale("pt", "BR"));
        formato.setMinimumFractionDigits(2);
        formato.setMaximumFractionDigits(2);

        valueLabel.setText(formato.format(total));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton addMovieButton;
    private JButton addRoomButton;
    private JCheckBox checkBox;
    private JButton dashboardButton;
    private JPanel dashboardPanel;
    private JButton helpButton;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JPanel jPanel1;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    private JButton movieButton;
    private JPanel moviesPanel;
    private JPanel navBarPanel;
    private JPanel parentPanel;
    private JButton roomButton;
    private JPanel roomsPanel;
    private JButton sessionButton;
    private JPanel sessionsPanel;
    private JButton signOutButton;
    private JTable tabelaFilmes;
    private JTable tabelaSalas;
    private JTable tabelaSessoes;
    private JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
