/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.educavalcante.cinemanager.views;

import br.com.educavalcante.cinemanager.controllers.SessaoController;
import br.com.educavalcante.cinemanager.models.entities.Sessao;
import br.com.educavalcante.cinemanager.models.entities.Filme;
import br.com.educavalcante.cinemanager.models.entities.Usuario;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

public class TelaFilme extends javax.swing.JFrame {
    private final SessaoController sessaoController;
    private final Filme filme;
    private final Usuario user;
    
    public TelaFilme(Filme filme, SessaoController sessaoController, Usuario usuario) {
        this.sessaoController = sessaoController;
        this.filme = filme;
        this.user = usuario;
        initComponents();
        
        this.setTitle(this.getTitle() + " - " + filme.getTitulo());
        titleLabel.setText(filme.getTitulo());
        genreLabel.setText(filme.getGenero());
        durationLabel.setText(filme.getDuracao() + " min");
        sinopseLabel.setText("<html>" + filme.getSinopse() + "</html>");
        
        carregarSessoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new JScrollPane();
        jPanel3 = new JPanel();
        jPanel6 = new JPanel();
        titleLabel = new JLabel();
        genreLabel = new JLabel();
        durationLabel = new JLabel();
        sinopseLabel = new JLabel();
        painelSessoes = new JPanel();
        jLabel1 = new JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CineManager");

        jPanel6.setBackground(Color.lightGray);
        jPanel6.setMaximumSize(new Dimension(80, 110));
        jPanel6.setMinimumSize(new Dimension(80, 110));
        jPanel6.setPreferredSize(new Dimension(80, 110));

        GroupLayout jPanel6Layout = new GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        titleLabel.setFont(new Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setText("jLabel1");

        genreLabel.setText("jLabel2");

        durationLabel.setText("jLabel3");

        sinopseLabel.setText("jLabel1");
        sinopseLabel.setMaximumSize(new Dimension(650, 300));

        GroupLayout painelSessoesLayout = new GroupLayout(painelSessoes);
        painelSessoes.setLayout(painelSessoesLayout);
        painelSessoesLayout.setHorizontalGroup(painelSessoesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painelSessoesLayout.setVerticalGroup(painelSessoesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );

        jLabel1.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Sessões disponíveis:");

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addComponent(sinopseLabel, GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(titleLabel, GroupLayout.PREFERRED_SIZE, 471, GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(durationLabel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(genreLabel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addComponent(painelSessoes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(titleLabel)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genreLabel)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(durationLabel)))
                .addGap(18, 18, 18)
                .addComponent(sinopseLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(painelSessoes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void carregarSessoes() {
        List<Sessao> sessoes = sessaoController.listarSessoesPorFilme(filme.getId());

        // agrupa por data (LocalDate)
        Map<LocalDate, List<Sessao>> porData = sessoes.stream()
                .collect(Collectors.groupingBy(s -> s.getDataHora().toLocalDate(),
                         LinkedHashMap::new,
                         Collectors.toList()));

        painelSessoes.removeAll();
        painelSessoes.setLayout(new BoxLayout(painelSessoes, BoxLayout.Y_AXIS));

        DateTimeFormatter fmtData = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        DateTimeFormatter fmtHora = DateTimeFormatter.ofPattern("HH:mm");

        for (Map.Entry<LocalDate, List<Sessao>> entry : porData.entrySet()) {
            JLabel labelData = new JLabel(entry.getKey().format(fmtData));
            labelData.setFont(labelData.getFont().deriveFont(Font.BOLD, 13f));
            labelData.setAlignmentX(Component.LEFT_ALIGNMENT);

            painelSessoes.add(labelData);
            painelSessoes.add(Box.createVerticalStrut(6));

            JPanel painelHorarios = new JPanel(new FlowLayout(FlowLayout.LEFT, 8, 0));
            painelHorarios.setOpaque(false);
            painelHorarios.setAlignmentX(Component.LEFT_ALIGNMENT);

            for (Sessao sessao : entry.getValue()) {
                JButton btnHorario = new JButton(sessao.getDataHora().format(fmtHora));
                btnHorario.setBackground(new Color(255, 140, 0));
                btnHorario.setForeground(Color.WHITE);
                btnHorario.setFont(btnHorario.getFont().deriveFont(Font.BOLD, 12f));
                btnHorario.setFocusPainted(false);
                btnHorario.setBorderPainted(false);
                btnHorario.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

                btnHorario.addActionListener(e -> {
                    new TelaSessao(filme, sessao, sessaoController, user).setVisible(true);
                });

                painelHorarios.add(btnHorario);
            }

            painelSessoes.add(painelHorarios);
            painelSessoes.add(Box.createVerticalStrut(14)); // espaço entre datas
        }

        painelSessoes.revalidate();
        painelSessoes.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel durationLabel;
    private JLabel genreLabel;
    private JLabel jLabel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JScrollPane jScrollPane1;
    private JPanel painelSessoes;
    private JLabel sinopseLabel;
    private JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
