/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.educavalcante.cinemanager.views;

import br.com.educavalcante.cinemanager.controllers.FilmeController;
import br.com.educavalcante.cinemanager.controllers.UsuarioController;
import br.com.educavalcante.cinemanager.models.DAOs.FilmeDAO;
import br.com.educavalcante.cinemanager.models.entities.Usuario;
import br.com.educavalcante.cinemanager.utils.Role;
import java.awt.CardLayout;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

public class TelaLogin extends javax.swing.JFrame {    
    private final UsuarioController usuarioController;
    private final CardLayout cardLayout;
    
    public TelaLogin(UsuarioController controller) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("CineManager");
        this.usuarioController = controller;
        this.cardLayout = (CardLayout) jPanel1.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jPanel2 = new JPanel();
        jLabel1 = new JLabel();
        loginButton = new JButton();
        passwordField = new JPasswordField();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        emailField = new JTextField();
        goToSignUpButton = new JButton();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        jPanel3 = new JPanel();
        jLabel4 = new JLabel();
        createEmailField = new JTextField();
        createPasswordField = new JPasswordField();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        nameField = new JTextField();
        jLabel7 = new JLabel();
        signUpButton = new JButton();
        backButton = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("CineManager");

        jPanel1.setLayout(new CardLayout());

        jLabel1.setFont(new Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Fazer Login:");

        loginButton.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        loginButton.setText("ENTRAR");
        loginButton.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        loginButton.addActionListener(this::loginButtonActionPerformed);

        passwordField.setText("admin123");
        passwordField.setToolTipText("Senha");

        jLabel2.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("E-mail:");

        jLabel3.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Senha:");

        emailField.setText("admin@cine.com");
        emailField.setToolTipText("Email");

        goToSignUpButton.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        goToSignUpButton.setText("CRIAR CONTA");
        goToSignUpButton.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        goToSignUpButton.addActionListener(this::goToSignUpButtonActionPerformed);

        jLabel8.setText("Emails: admin@cine.com e cliente@cine.com (ou crie uma conta, se necessário)");

        jLabel9.setText("Senhas: admin123 e cliente123");

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(passwordField, GroupLayout.PREFERRED_SIZE, 308, GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE))
                            .addComponent(emailField, GroupLayout.PREFERRED_SIZE, 308, GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(loginButton, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(goToSignUpButton, GroupLayout.PREFERRED_SIZE, 121, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(emailField, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(passwordField, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(goToSignUpButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, "loginCard");

        jLabel4.setFont(new Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Criar conta:");

        createEmailField.setToolTipText("Email");

        createPasswordField.setToolTipText("Senha");

        jLabel5.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("E-mail:");

        jLabel6.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Senha:");

        nameField.setToolTipText("Email");

        jLabel7.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nome:");

        signUpButton.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        signUpButton.setText("CRIAR CONTA");
        signUpButton.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        signUpButton.addActionListener(this::signUpButtonActionPerformed);

        backButton.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        backButton.setText("VOLTAR");
        backButton.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        backButton.addActionListener(this::backButtonActionPerformed);

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(createPasswordField, GroupLayout.PREFERRED_SIZE, 308, GroupLayout.PREFERRED_SIZE)
                            .addComponent(createEmailField, GroupLayout.PREFERRED_SIZE, 308, GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameField, GroupLayout.PREFERRED_SIZE, 308, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backButton, GroupLayout.PREFERRED_SIZE, 121, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signUpButton, GroupLayout.PREFERRED_SIZE, 121, GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameField, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createEmailField, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addComponent(createPasswordField, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpButton)
                    .addComponent(backButton))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, "signUpCard");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String email = emailField.getText().trim();
        String senhaPlana = new String(passwordField.getPassword()).trim();

        Usuario user = usuarioController.entrar(email, senhaPlana);

        if(user != null) {
            FilmeDAO filmeDAO = new FilmeDAO();
            FilmeController filmeController = new FilmeController(filmeDAO);
            
            if(user.getRole() == Role.ADMIN) {
                new TelaAdmin(filmeController).setVisible(true);
            } else {
                new TelaCliente(filmeController, user).setVisible(true);
            }
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "E-mail ou senha incorretos.", "Erro de login", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void goToSignUpButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_goToSignUpButtonActionPerformed
        cardLayout.show(jPanel1, "signUpCard");
        emailField.setText("");
        passwordField.setText("");
    }//GEN-LAST:event_goToSignUpButtonActionPerformed

    private void signUpButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        String nome = nameField.getText().trim();
        String email = createEmailField.getText().trim();
        String senha = new String(createPasswordField.getPassword()).trim();
        
        Usuario user = usuarioController.criarConta(nome, email, senha, Role.CLIENTE);
        
        if(user != null) {
            FilmeDAO filmeDAO = new FilmeDAO();
            FilmeController filmeController = new FilmeController(filmeDAO);
            
            if(user.getRole() == Role.ADMIN) {
                new TelaAdmin(filmeController).setVisible(true);
            } else {
                new TelaCliente(filmeController, user).setVisible(true);
            }
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao criar conta.", "Erro de cadastro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void backButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        cardLayout.show(jPanel1, "loginCard");
        nameField.setText("");
        createEmailField.setText("");
        createPasswordField.setText("");
    }//GEN-LAST:event_backButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton backButton;
    private JTextField createEmailField;
    private JPasswordField createPasswordField;
    private JTextField emailField;
    private JButton goToSignUpButton;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JButton loginButton;
    private JTextField nameField;
    private JPasswordField passwordField;
    private JButton signUpButton;
    // End of variables declaration//GEN-END:variables
}
