/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.educavalcante.cinemanager.views;

import br.com.educavalcante.cinemanager.controllers.FilmeController;
import br.com.educavalcante.cinemanager.controllers.IngressoController;
import br.com.educavalcante.cinemanager.controllers.SalaController;
import br.com.educavalcante.cinemanager.controllers.SessaoController;
import br.com.educavalcante.cinemanager.controllers.UsuarioController;
import br.com.educavalcante.cinemanager.models.DAOs.IngressoDAO;
import br.com.educavalcante.cinemanager.models.DAOs.SalaDAO;
import br.com.educavalcante.cinemanager.models.DAOs.SessaoDAO;
import br.com.educavalcante.cinemanager.models.DAOs.UsuarioDAO;
import br.com.educavalcante.cinemanager.models.entities.Filme;
import br.com.educavalcante.cinemanager.models.entities.Usuario;
import br.com.educavalcante.cinemanager.models.entities.Ingresso;
import br.com.educavalcante.cinemanager.models.entities.Sala;
import br.com.educavalcante.cinemanager.utils.ExportadorIngressos;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

public class TelaCliente extends javax.swing.JFrame {
    private final CardLayout cardLayout;
    private final FilmeController filmeController;
    private final IngressoController ingressoController;
    private final SessaoController sessaoController;
    private final SalaController salaController;
    private final Usuario user;
    
    public TelaCliente(FilmeController filmeController, Usuario usuario) {
        initComponents();
        this.cardLayout = (CardLayout) parentPanel.getLayout();
        this.filmeController = filmeController;
        this.ingressoController = new IngressoController(new IngressoDAO());
        this.sessaoController = new SessaoController(new SessaoDAO(), ingressoController);
        this.salaController = new SalaController(new SalaDAO());
        this.user = usuario;
        
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(16);
        
        EventQueue.invokeLater(() -> {
            carregarFilmes();
            carregarIngressos();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navBarPanel = new JPanel();
        homeButton = new JButton();
        ticketButton = new JButton();
        signOutButton = new JButton();
        parentPanel = new JPanel();
        homePanel = new JPanel();
        jScrollPane1 = new JScrollPane();
        painelLista = new JPanel();
        ticketPanel = new JPanel();
        jScrollPane2 = new JScrollPane();
        painelIngressos = new JPanel();
        jPanel1 = new JPanel();
        exportButton = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("CineManager");

        navBarPanel.setBackground(new Color(51, 51, 51));

        homeButton.setText("Tela Inicial");
        homeButton.addActionListener(this::homeButtonActionPerformed);

        ticketButton.setText("Meus Ingressos");
        ticketButton.addActionListener(this::ticketButtonActionPerformed);

        signOutButton.setText("Sair");
        signOutButton.addActionListener(this::signOutButtonActionPerformed);

        GroupLayout navBarPanelLayout = new GroupLayout(navBarPanel);
        navBarPanel.setLayout(navBarPanelLayout);
        navBarPanelLayout.setHorizontalGroup(navBarPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(navBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton)
                .addGap(18, 18, 18)
                .addComponent(ticketButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signOutButton)
                .addContainerGap())
        );
        navBarPanelLayout.setVerticalGroup(navBarPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, navBarPanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(navBarPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(homeButton)
                    .addComponent(ticketButton)
                    .addComponent(signOutButton))
                .addContainerGap())
        );

        parentPanel.setLayout(new CardLayout());

        GroupLayout painelListaLayout = new GroupLayout(painelLista);
        painelLista.setLayout(painelListaLayout);
        painelListaLayout.setHorizontalGroup(painelListaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        painelListaLayout.setVerticalGroup(painelListaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(painelLista);

        GroupLayout homePanelLayout = new GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(homePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        homePanelLayout.setVerticalGroup(homePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        parentPanel.add(homePanel, "homeCard");

        GroupLayout painelIngressosLayout = new GroupLayout(painelIngressos);
        painelIngressos.setLayout(painelIngressosLayout);
        painelIngressosLayout.setHorizontalGroup(painelIngressosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        painelIngressosLayout.setVerticalGroup(painelIngressosLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(painelIngressos);

        exportButton.setText("Exportar ingressos");
        exportButton.addActionListener(this::exportButtonActionPerformed);

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exportButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(exportButton)
        );

        GroupLayout ticketPanelLayout = new GroupLayout(ticketPanel);
        ticketPanel.setLayout(ticketPanelLayout);
        ticketPanelLayout.setHorizontalGroup(ticketPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ticketPanelLayout.setVerticalGroup(ticketPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, ticketPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 478, GroupLayout.PREFERRED_SIZE))
        );

        parentPanel.add(ticketPanel, "ticketCard");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(navBarPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(parentPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navBarPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parentPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        cardLayout.show(parentPanel, "homeCard");
    }//GEN-LAST:event_homeButtonActionPerformed

    private void ticketButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_ticketButtonActionPerformed
        cardLayout.show(parentPanel, "ticketCard");
        EventQueue.invokeLater(() -> {
            carregarIngressos();
        });
    }//GEN-LAST:event_ticketButtonActionPerformed

    private void signOutButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_signOutButtonActionPerformed
        new TelaLogin(new UsuarioController(new UsuarioDAO())).setVisible(true);
        dispose();
    }//GEN-LAST:event_signOutButtonActionPerformed

    private void exportButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        List<Ingresso> listaIngressos = ingressoController.buscarIngressosPorUsuario(user.getId());
        if (listaIngressos.isEmpty() || listaIngressos == null) {
            JOptionPane.showMessageDialog(this, "Nenhum ingresso encontrado.");
            return;
        }
        
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Salvar ingressos");
        int opcao = chooser.showSaveDialog(this);

        if (opcao == JFileChooser.APPROVE_OPTION) {            
            File arquivo = chooser.getSelectedFile();

            try {
                ExportadorIngressos.exportarTXT(
                        listaIngressos,
                        arquivo.getAbsolutePath() + ".txt"
                );
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao exportar ingressos", "Erro", JOptionPane.ERROR_MESSAGE);
            }

            JOptionPane.showMessageDialog(this, "Arquivo exportado com sucesso!");
        }
    }//GEN-LAST:event_exportButtonActionPerformed

    public void carregarFilmes() {
        List<Filme> filmes = filmeController.listarFilmesEmCartaz();

        painelLista.removeAll();
        painelLista.setLayout(new BoxLayout(painelLista, BoxLayout.Y_AXIS));

        for (Filme f : filmes) {
            painelLista.add(criarCardFilme(f));
            painelLista.add(Box.createVerticalStrut(8));
        }

        painelLista.revalidate();
        painelLista.repaint();
    }
    
    private JPanel criarCardFilme(Filme filme) {
        JPanel card = new JPanel();
        card.setLayout(new BoxLayout(card, BoxLayout.X_AXIS));
        card.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(Color.LIGHT_GRAY),
            BorderFactory.createEmptyBorder(10, 10, 10, 10)
        ));
        card.setMaximumSize(new Dimension(Integer.MAX_VALUE, 120));
        card.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        JPanel capa = new JPanel();
        capa.setPreferredSize(new Dimension(70, 100));
        capa.setMinimumSize(new Dimension(70, 100));
        capa.setMaximumSize(new Dimension(70, 100));
        capa.setBackground(Color.LIGHT_GRAY);
        card.add(capa);

        card.add(Box.createHorizontalStrut(12));

        JPanel infos = new JPanel();
        infos.setLayout(new BoxLayout(infos, BoxLayout.Y_AXIS));

        JLabel titulo = new JLabel(filme.getTitulo());
        titulo.setFont(titulo.getFont().deriveFont(Font.BOLD, 14f));

        JLabel detalhes = new JLabel(filme.getGenero() + " • " + filme.getDuracao() + " min");
        detalhes.setForeground(Color.GRAY);

        String sinopseTexto = filme.getSinopse().length() > 200
                ? filme.getSinopse().substring(0, 200) + "..."
                : filme.getSinopse();
        JLabel sinopse = new JLabel("<html>" + sinopseTexto + "</html>");
        sinopse.setFont(sinopse.getFont().deriveFont(12f));
        sinopse.setMaximumSize(new Dimension(550, Integer.MAX_VALUE));
        sinopse.setPreferredSize(new Dimension(550, 40));

        infos.add(titulo);
        infos.add(Box.createVerticalStrut(4));
        infos.add(detalhes);
        infos.add(Box.createVerticalStrut(6));
        infos.add(sinopse);

        card.add(infos);

        card.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                new TelaFilme(filme, sessaoController, user).setVisible(true);
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                card.setBackground(new Color(51, 51, 51));
                infos.setBackground(new Color(51, 51, 51));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                card.setBackground(null);
                infos.setBackground(null);
            }
        });

        return card;
    }
    
    public void carregarIngressos() {
        List<Ingresso> ingressos = ingressoController.buscarIngressosPorUsuario(user.getId());

        painelIngressos.removeAll();
        painelIngressos.setLayout(new BoxLayout(painelIngressos, BoxLayout.Y_AXIS));

        if (ingressos.isEmpty()) {
            JLabel lblVazio = new JLabel("Você ainda não tem ingressos.");
            lblVazio.setForeground(Color.GRAY);
            lblVazio.setAlignmentX(Component.CENTER_ALIGNMENT);
            painelIngressos.add(Box.createVerticalGlue());
            painelIngressos.add(lblVazio);
            painelIngressos.add(Box.createVerticalGlue());
        } else {
            for (Ingresso i : ingressos) {
                painelIngressos.add(criarCardIngresso(i));
                painelIngressos.add(Box.createVerticalStrut(10));
            }
        }

        painelIngressos.revalidate();
        painelIngressos.repaint();
    }
    
    private JPanel criarCardIngresso(Ingresso ingresso) {
        JPanel card = new JPanel();
        card.setLayout(new BoxLayout(card, BoxLayout.Y_AXIS));
        card.setBorder(BorderFactory.createLineBorder(new Color(35, 35, 35)));
        card.setMaximumSize(new Dimension(Integer.MAX_VALUE, 240));
        card.setBackground(new Color(51, 51, 51));

        JPanel header = new JPanel(new BorderLayout());
        header.setBackground(new Color(0, 51, 153));
        header.setBorder(BorderFactory.createEmptyBorder(10, 14, 10, 14));

        JPanel headerLeft = new JPanel();
        headerLeft.setLayout(new BoxLayout(headerLeft, BoxLayout.Y_AXIS));
        headerLeft.setOpaque(false);

        JLabel lblIngresso = new JLabel("INGRESSO");
        lblIngresso.setFont(lblIngresso.getFont().deriveFont(Font.PLAIN, 10f));
        lblIngresso.setForeground(new Color(0, 204, 255));

        JLabel lblFilme = new JLabel(ingresso.getFilme());
        lblFilme.setForeground(Color.WHITE);
        lblFilme.setFont(lblFilme.getFont().deriveFont(Font.BOLD, 15f));

        headerLeft.add(lblIngresso);
        headerLeft.add(lblFilme);

        JLabel lblId = new JLabel("#" + String.format("%04d", ingresso.getId()));
        lblId.setFont(lblId.getFont().deriveFont(Font.BOLD, 12f));
        lblId.setForeground(new Color(0, 204, 255));

        header.add(headerLeft, BorderLayout.WEST);
        header.add(lblId, BorderLayout.EAST);
        card.add(header);

        JPanel grid = new JPanel(new GridLayout(3, 2, 8, 6));
        grid.setBorder(BorderFactory.createEmptyBorder(10, 14, 10, 14));
        grid.setBackground(null);

        DateTimeFormatter fmtData = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        DateTimeFormatter fmtHora = DateTimeFormatter.ofPattern("HH:mm");

        Sala sala = salaController.buscarSalaPorNumero(ingresso.getNumeroSala());
        
        int assentoReal = (ingresso.getNumeroFileira() - 1) * sala.getTotalAssentosPorFileira() + ingresso.getNumeroAssento();
        grid.add(criarCampo("Data", ingresso.getDataHora().format(fmtData)));
        grid.add(criarCampo("Hora", ingresso.getDataHora().format(fmtHora)));
        grid.add(criarCampo("Sessão", "#" + ingresso.getSessaoId()));
        grid.add(criarCampo("Sala", "Sala " + ingresso.getNumeroSala()));
        grid.add(criarCampo("Fileira", String.valueOf(ingresso.getNumeroFileira())));
        grid.add(criarCampo("Assento", String.valueOf(assentoReal)));

        card.add(grid);

        JSeparator sep = new JSeparator();
        sep.setForeground(new Color(35, 35, 35));
        sep.setMaximumSize(new Dimension(Integer.MAX_VALUE, 1));
        card.add(sep);

        JPanel footer = new JPanel(new BorderLayout());
        footer.setBorder(BorderFactory.createEmptyBorder(8, 14, 10, 14));
        footer.setBackground(null);

        JLabel lblPrecoLabel = new JLabel("Preço pago");
        lblPrecoLabel.setForeground(Color.GRAY);
        lblPrecoLabel.setFont(lblPrecoLabel.getFont().deriveFont(11f));

        JLabel lblPreco = new JLabel(String.format("R$ %.2f", ingresso.getPreco()));
        lblPreco.setFont(lblPreco.getFont().deriveFont(Font.BOLD, 14f));

        footer.add(lblPrecoLabel, BorderLayout.WEST);
        footer.add(lblPreco, BorderLayout.EAST);
        card.add(footer);

        return card;
    }

    private JPanel criarCampo(String label, String valor) {
        JPanel campo = new JPanel();
        campo.setLayout(new BoxLayout(campo, BoxLayout.Y_AXIS));
        campo.setBackground(null);

        JLabel lbl = new JLabel(label);
        lbl.setFont(lbl.getFont().deriveFont(10f));
        lbl.setForeground(Color.GRAY);

        JLabel val = new JLabel(valor);
        val.setFont(val.getFont().deriveFont(Font.BOLD, 13f));

        campo.add(lbl);
        campo.add(val);
        return campo;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton exportButton;
    private JButton homeButton;
    private JPanel homePanel;
    private JPanel jPanel1;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JPanel navBarPanel;
    private JPanel painelIngressos;
    private JPanel painelLista;
    private JPanel parentPanel;
    private JButton signOutButton;
    private JButton ticketButton;
    private JPanel ticketPanel;
    // End of variables declaration//GEN-END:variables
}
